#!/usr/bin/env bash
# Kissing family autonomous push loop — one FIXED-n problem per invocation.
#
# Mirrors P7's scripts/prime/campaign_loop.sh, simplified: kissing targets are
# fixed-n (n=605 / n=842), so there is no rung ladder — every iteration is one
# cron_polish_submit.py tick:
#
#   polish from warm-start -> honest re-score (overlap_loss_mpmath, not the
#   polish surrogate) -> 6-gate auto_submit.try_submit -> submit IFF it strictly
#   beats live arena #1 by the margin floor. All submission gating (kill switch,
#   triple-verify, daily cap, 1h throttle, SOTA, flock'd audit) lives in the
#   gate chain; this wrapper only supplies the persistent loop + caffeinate +
#   a shell-level kill switch + a DRAFT writeup on success.
#
# Usage:
#   scripts/kissing_number/push_loop.sh <problem_id> <slug> [budget_sec]
#   scripts/kissing_number/push_loop.sh 24 kissing-number-d11-605 1200
#   scripts/kissing_number/push_loop.sh 25 kissing-number-d12-842 1200
#
# Kill switch (either — checked before/after every tick):
#   touch results/problem-<id>-<slug>/STOP              # shell-level
#   EINSTEIN_AUTO_SUBMIT=0 scripts/kissing_number/push_loop.sh ...   # gate 1
#
# Stall guard: MAX_HOLD_STREAK consecutive no-submit ticks -> stop for human review.
#
# POST draft: on a gate-passing submission, a DRAFT writeup is dropped in
# mb/posts/drafts/ and NOTHING is posted externally — axiom A2 makes the wiki the
# only publication channel; the draft is for human review, not auto-sending.
set -u
cd "$(dirname "$0")/../.." || exit 1

PID="${1:?usage: push_loop.sh <problem_id> <slug> [budget_sec]}"
SLUG="${2:?usage: push_loop.sh <problem_id> <slug> [budget_sec]}"
BUDGET="${3:-1200}"
MAX_HOLD_STREAK="${MAX_HOLD_STREAK:-24}"   # ~24 idle ticks -> human review
SLEEP_BETWEEN="${SLEEP_BETWEEN:-60}"       # gap between ticks (throttle is 1h in-gate)

OUT="results/problem-${PID}-${SLUG}"
mkdir -p "$OUT"
LOG="$OUT/push_loop.log"
STOP="$OUT/STOP"
AUDIT="../mb/logs/auto-submit.md"
DRAFTS="../mb/posts/drafts"

# Keep the machine awake for the lifetime of this loop (dies with $$).
command -v caffeinate >/dev/null 2>&1 && caffeinate -ims -w $$ &

ts() { date +"%m-%d %H:%M"; }
log() { echo "[$(ts)] $*" | tee -a "$LOG"; }
stop() { log "STOP: $*"; date > "$OUT/PUSH_LOOP_DONE"; exit 0; }

# Count rows in the flock'd audit log that are BOTH this problem and a submit.
# Fields split on '|': [3]=problem_id, [5]=decision.
submitted_count() {
  [ -f "$AUDIT" ] || { echo 0; return; }
  awk -F'|' -v p="$PID" '$3+0==p && $5==" submitted " {c++} END{print c+0}' "$AUDIT"
}

log "PUSH LOOP START p$PID ($SLUG) budget=${BUDGET}s (kill: touch $STOP)"
HOLD_STREAK=0

while :; do
  [ -f "$STOP" ] && stop "kill switch ($STOP)"

  before=$(submitted_count)
  log "── tick p$PID"
  uv run python -u scripts/kissing_number/cron_polish_submit.py \
    --problem-id "$PID" --slug "$SLUG" --budget "$BUDGET" >>"$LOG" 2>&1
  after=$(submitted_count)

  [ -f "$STOP" ] && stop "kill switch ($STOP)"

  if [ "$after" -gt "$before" ]; then
    HOLD_STREAK=0
    line=$(awk -F'|' -v p="$PID" '$3+0==p && $5==" submitted "' "$AUDIT" | tail -1)
    log "SUBMITTED: $line"
    mkdir -p "$DRAFTS"
    draft="$DRAFTS/kissing-p${PID}-$(date +%Y%m%dT%H%M%SZ).md"
    {
      echo "# DRAFT — kissing p$PID ($SLUG) submission"
      echo
      echo "Auto-generated by push_loop.sh on a gate-passing submission. DRAFT ONLY:"
      echo "nothing is posted externally (axiom A2 — the wiki is the channel). For"
      echo "human review before any sharing decision."
      echo
      echo "Audit row:"
      echo
      echo "    ${line# }"
    } >"$draft"
    log "draft writeup: $draft"
  else
    HOLD_STREAK=$((HOLD_STREAK + 1))
    log "HELD (streak $HOLD_STREAK/$MAX_HOLD_STREAK) — see gate reason in $AUDIT"
    [ "$HOLD_STREAK" -ge "$MAX_HOLD_STREAK" ] &&
      stop "held $MAX_HOLD_STREAK ticks — gains stalled or board moved; human review"
  fi

  sleep "$SLEEP_BETWEEN"
done
